const $=(q,e=document)=>e.querySelector(q),$$=(q,e=document)=>[...e.querySelectorAll(q)];
let cart=JSON.parse(localStorage.getItem("weddingCart")||"[]");
const currency=()=>localStorage.getItem("currency")||WEDDING.currencies.default;
const money=v=>new Intl.NumberFormat(undefined,{style:"currency",currency:currency()}).format(v*(WEDDING.currencies.rates[currency()]||1));
function common(){$$("[data-brand]").forEach(e=>e.textContent=`${WEDDING.couple.person1} & ${WEDDING.couple.person2}`);$$("[data-year]").forEach(e=>e.textContent=new Date(WEDDING.wedding.dateISO).getFullYear())}
function home(){if(!$("#home"))return;$("#hero").innerHTML=`${WEDDING.couple.person1} <span class="amp">&</span> ${WEDDING.couple.person2}`;$("#date").textContent=WEDDING.wedding.dateDisplay;$("#msg").textContent=WEDDING.intro.message;$("#verse").textContent=WEDDING.story.verse;$("#storycopy").innerHTML=WEDDING.story.paragraphs.map(x=>`<p>${x}</p>`).join("");$("#event").innerHTML=`<article class="card center"><h3>${WEDDING.wedding.programme}</h3><p>${WEDDING.wedding.dateDisplay}</p><p>${WEDDING.wedding.reception}</p></article><article class="card center"><h3>${WEDDING.wedding.venue}</h3><p>${WEDDING.wedding.city}</p></article><article class="card center"><h3>Colour Code</h3><p>${WEDDING.wedding.colourCode}</p></article>`;$("#cats").innerHTML=WEDDING.categories.map(c=>`<article class="card center"><div style="font-size:2rem">${c.icon}</div><h3>${c.name}</h3><p>${c.description}</p><a class="btn alt" href="registry.html?cat=${encodeURIComponent(c.name)}">View</a></article>`).join("");$("#faq").innerHTML=WEDDING.faq.map(x=>`<details><summary>${x.q}</summary><p>${x.a}</p></details>`).join("");$("#contacts").innerHTML=WEDDING.contacts.map(c=>`<article class="card center"><h3>${c.name}</h3><p>${c.phone}</p><a class="btn alt" target="_blank" href="https://wa.me/${c.whatsapp}">WhatsApp</a></article>`).join("")}
function registry(){if(!$("#products"))return;const p=new URLSearchParams(location.search),cat=p.get("cat")||"All";$("#filter").innerHTML=["All",...WEDDING.categories.map(x=>x.name)].map(x=>`<option ${x==cat?"selected":""}>${x}</option>`).join("");$("#cur").innerHTML=Object.keys(WEDDING.currencies.rates).map(x=>`<option ${x==currency()?"selected":""}>${x}</option>`).join("");const list=WEDDING.items.filter(x=>cat=="All"||x.category==cat);$("#products").innerHTML=list.map(x=>`<article class="card"><div class="ph">Gift image</div><p><span class="badge">${x.category}</span></p><h3>${x.name}</h3><p class="price">${money(x.priceEUR)}</p><button class="btn" onclick="add(${x.id})">Add gift</button></article>`).join("");$("#filter").onchange=e=>location.href=e.target.value=="All"?"registry.html":`registry.html?cat=${encodeURIComponent(e.target.value)}`;$("#cur").onchange=e=>{localStorage.setItem("currency",e.target.value);location.reload()};renderCart()}
function add(id){cart.push(WEDDING.items.find(x=>x.id==id));localStorage.setItem("weddingCart",JSON.stringify(cart));renderCart()}
function renderCart(){if($("#cartcount"))$("#cartcount").textContent=cart.length}
function rsvp(){if(!$("#rsvpform"))return;$("#rsvpform").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),t=`RSVP\nName: ${f.get("name")}\nAttendance: ${f.get("attendance")}\nGuests: ${f.get("guests")}\nMessage: ${f.get("message")||""}`;window.open(`https://wa.me/${WEDDING.contacts[0].whatsapp}?text=${encodeURIComponent(t)}`,"_blank")}}
document.addEventListener("DOMContentLoaded",()=>{common();home();registry();rsvp()});