const WEDDING = {
  couple: { person1: "Ibrahim", person2: "Khadijat", hashtag: "#OurUnion2027" },
  wedding: { dateISO: "2026-10-03T10:00:00", dateDisplay: "02PM, 02 Oct 2026, DSO beside GT Plaza. Lokoja, Kogi state", city: "09AM, 3rd Oct 2026, Motel5 hotel Before NNPC mega station, Felele, Lokoja, Kogi state, Nigeria", venue: "Wedding Fatiha", programme: "Engagement", reception: "Reception follows immediately", colourCode: "Emerald, Ivory & Gold" },
  intro: { eyebrow: "Welcome to our", message: "Thank you for celebrating our love and supporting our new beginning." },
  story: { verse: "“And of His signs is that He created for you from yourselves mates that you may find tranquility in them, and He placed between you affection and mercy.” — Qur'an 30:21", paragraphs: ["Write how the couple met here.", "Add an important milestone in their journey.", "Close with a message of gratitude to family and friends."], closing: "Two hearts, one journey, a lifetime ahead." },
  contacts: [{ name: "RSVP Contact 1", phone: "+23412345678", whatsapp: "000000000000" }, { name: "RSVP Contact 2", phone: "+000000000000", whatsapp: "000000000000" }],
  currencies: { default: "EUR", rates: { EUR: 1, NGN: 1800, USD: 1.16 } },
  categories: [{ name: "Home & Living", icon: "⌂", description: "Useful pieces for our new home." }, { name: "Honeymoon Fund", icon: "✈", description: "Help us create beautiful memories together." }, { name: "Cash Gift", icon: "♡", description: "A flexible contribution toward our new chapter." }, { name: "Faith & Essentials", icon: "☾", description: "Meaningful essentials for our home." }],
  items: [{ id: 1, category: "Home & Living", name: "Cookware Set", priceEUR: 90 }, { id: 2, category: "Home & Living", name: "Dinnerware Set", priceEUR: 65 }, { id: 3, category: "Home & Living", name: "Blender", priceEUR: 55 }, { id: 4, category: "Faith & Essentials", name: "Prayer Rug Set", priceEUR: 35 }, { id: 5, category: "Honeymoon Fund", name: "Honeymoon Contribution", priceEUR: 100 }, { id: 6, category: "Cash Gift", name: "Wedding Cash Gift", priceEUR: 50 }],
  faq: [{ q: "How can I contribute to the registry?", a: "Browse the registry, choose a gift or fund and add it to your gift basket." }, { q: "Can I give a cash gift?", a: "Yes. Replace the demo checkout with your preferred secure payment provider." }, { q: "Will there be a gift table at the venue?", a: "Edit this answer to match your wedding arrangements." }, { q: "Can I contribute in another currency?", a: "The template includes a display currency switcher. Real payments require a payment integration." }]
};
